services:
  # Gemma 3 27B IT Abliterated Vision with Vulkan AMD iGPU (Windows - Software Mode)
  gemma3-27b-it-abliterated-vulkan-amd-windows:
    build:
      context: .
      dockerfile: Dockerfile.vulkan-amd-igpu
    container_name: gemma3-27b-it-abliterated-vulkan-amd-windows
    ports:
      - "8085:8080"
    # No device access for Windows Docker Desktop
    # devices:
    #   - /dev/kfd:/dev/kfd  # Not available in Windows Docker
    #   - /dev/dri:/dev/dri  # Not available in Windows Docker
    
    # ROCm + Vulkan environment variables for AMD 8945HS (software mode testing)
    environment:
      - MODEL_SCRIPT=gemma3-27b-it-abliterated-vulkan-amd
      - HSA_OVERRIDE_GFX_VERSION=11.0.2
      - HCC_AMDGPU_TARGET=gfx1103
      - ROCM_VERSION=6.4.1
      - HSA_ENABLE_SDMA=0
      - ROCR_VISIBLE_DEVICES=0
      - HIP_VISIBLE_DEVICES=0
      # Vulkan software fallback mode
      - VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json
      - AMD_VULKAN_ICD=RADV
      - MESA_VK_VERSION_OVERRIDE=1.3
      - GGML_VULKAN_DEVICE=0
      - GGML_VULKAN=1
    # Model cache volume (separate for Windows)
    volumes:
      - llama_cache_windows:/root/.cache/llama
    restart: unless-stopped

  # Mistral Small 3.2 24B Vision with Vulkan AMD iGPU (Windows - Software Mode)
  mistral-small-3.2-24b-vulkan-amd-windows:
    build:
      context: .
      dockerfile: Dockerfile.vulkan-amd-igpu
    container_name: mistral-small-3.2-24b-vulkan-amd-windows
    ports:
      - "8085:8080"
    # No device access for Windows Docker Desktop
    # devices:
    #   - /dev/kfd:/dev/kfd  # Not available in Windows Docker
    #   - /dev/dri:/dev/dri  # Not available in Windows Docker
    
    # ROCm + Vulkan environment variables (software mode testing)
    environment:
      - MODEL_SCRIPT=mistral-small-3.2-24b-vulkan-amd
      - HSA_OVERRIDE_GFX_VERSION=11.0.2
      - HCC_AMDGPU_TARGET=gfx1103
      - ROCM_VERSION=6.4.1
      - HSA_ENABLE_SDMA=0
      - ROCR_VISIBLE_DEVICES=0
      - HIP_VISIBLE_DEVICES=0
      # Vulkan software fallback mode
      - VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json
      - AMD_VULKAN_ICD=RADV
      - MESA_VK_VERSION_OVERRIDE=1.3
      - GGML_VULKAN_DEVICE=0
      - GGML_VULKAN=1
    # Model cache volume (separate for Windows)
    volumes:
      - llama_cache_windows:/root/.cache/llama
    restart: unless-stopped

volumes:
  llama_cache_windows:
