services:
  # Gemma 3 27B IT Abliterated Vision with Enhanced Vulkan AMD iGPU
  gemma3-27b-it-abliterated-vulkan-amd:
    build:
      context: .
      dockerfile: Dockerfile.vulkan-amd-igpu
    container_name: gemma3-27b-it-abliterated-vulkan-amd
    ports:
      - "8085:8080"
    # AMD iGPU device access - Toxantron methodology (what made OpenCL work!)
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    # Group permissions for render and video groups
    group_add:
      - "${RENDER_GROUP_ID:-102}"
      - "${VIDEO_GROUP_ID:-44}"
    # Combined ROCm + Vulkan environment variables for AMD 8945HS (gfx1103)
    environment:
      - MODEL_SCRIPT=gemma3-27b-it-abliterated-vulkan-amd
      - HSA_OVERRIDE_GFX_VERSION=11.0.2
      - HCC_AMDGPU_TARGET=gfx1103
      - ROCM_VERSION=6.4.1
      - HSA_ENABLE_SDMA=0
      - ROCR_VISIBLE_DEVICES=0
      - HIP_VISIBLE_DEVICES=0
      # Vulkan-specific optimizations
      - VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json
      - AMD_VULKAN_ICD=RADV
      - RADV_PERFTEST=aco,llvm
      - MESA_VK_VERSION_OVERRIDE=1.3
      - GGML_VULKAN_DEVICE=0
      - GGML_VULKAN=1
      - GGML_FORCE_VULKAN=1
    # Model cache volume
    volumes:
      - llama_cache:/root/.cache/llama
    restart: unless-stopped

  # Mistral Small 3.2 24B Vision with Enhanced Vulkan AMD iGPU
  mistral-small-3.2-24b-vulkan-amd:
    build:
      context: .
      dockerfile: Dockerfile.vulkan-amd-igpu
    container_name: mistral-small-3.2-24b-vulkan-amd
    ports:
      - "8085:8080"
    # AMD iGPU device access - Toxantron methodology
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    # Group permissions for render and video groups
    group_add:
      - "${RENDER_GROUP_ID:-102}"
      - "${VIDEO_GROUP_ID:-44}"
    # Combined ROCm + Vulkan environment variables
    environment:
      - MODEL_SCRIPT=mistral-small-3.2-24b-vulkan-amd
      - HSA_OVERRIDE_GFX_VERSION=11.0.2
      - HCC_AMDGPU_TARGET=gfx1103
      - ROCM_VERSION=6.4.1
      - HSA_ENABLE_SDMA=0
      - ROCR_VISIBLE_DEVICES=0
      - HIP_VISIBLE_DEVICES=0
      # Vulkan-specific optimizations
      - VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json
      - AMD_VULKAN_ICD=RADV
      - RADV_PERFTEST=aco,llvm
      - MESA_VK_VERSION_OVERRIDE=1.3
      - GGML_VULKAN_DEVICE=0
      - GGML_VULKAN=1
      - GGML_FORCE_VULKAN=1
    # Model cache volume
    volumes:
      - llama_cache:/root/.cache/llama
    restart: unless-stopped

volumes:
  llama_cache:
