services:
  # AMD iGPU ROCm Base Container - Exact copy from Toxantron/iGPU-Docker
  rocm-igpu-base:
    image: rocm-igpu:latest
    build:
      context: .
      dockerfile: Dockerfile.rocm-base
    container_name: rocm-igpu-base
    # Device access for AMD iGPU - exactly as specified by Toxantron
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    # Group permissions for render and video groups (fixed duplicates)
    group_add:
      - "${RENDER_GROUP_ID:-102}"
      - "${VIDEO_GROUP_ID:-44}"
    # Interactive shell
    stdin_open: true
    tty: true
    restart: unless-stopped
