services:
  # AMD iGPU ROCm Base Container - Exact copy from Toxantron/iGPU-Docker
  rocm-igpu-base:
    image: rocm-igpu:latest
    build:
      context: .
      dockerfile: Dockerfile.rocm-base
    container_name: rocm-igpu-base
    # Device access for AMD iGPU - exactly as specified by Toxantron
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    # Group permissions for render and video groups (fixed duplicates)
    group_add:
      - "${RENDER_GROUP_ID:-102}"
      - "${VIDEO_GROUP_ID:-44}"
    # Interactive shell
    stdin_open: true
    tty: true
    restart: unless-stopped

  # ROCm LLaMA.cpp Server with AMD iGPU support
  rocm-llama-server:
    build:
      context: .
      dockerfile: Dockerfile.rocm-llama-server
    container_name: rocm-llama-server
    ports:
      - "8085:8080"
    # Device access for AMD iGPU
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    # Group permissions for render and video groups
    group_add:
      - "${RENDER_GROUP_ID:-102}"
      - "${VIDEO_GROUP_ID:-44}"
    # ROCm environment variables
    environment:
      - MODEL_SCRIPT=gemma3-27b-it-abliterated-rocm
      - HSA_OVERRIDE_GFX_VERSION=11.0.2
      - HCC_AMDGPU_TARGET=gfx1103
      - ROCM_VERSION=6.4.1
      - HSA_ENABLE_SDMA=0
      - ROCR_VISIBLE_DEVICES=0
      - HIP_VISIBLE_DEVICES=0
    # Model cache volume
    volumes:
      - llama_cache:/root/.cache/llama
    restart: unless-stopped

volumes:
  llama_cache:
